export const FREE_TESTS_DATA = {
  categories: ["All", "AIIMS", "NORCET", "ESIC", "RRB", "DSSSB", "KGMU", "SGPGI", "RML", "DHS", "DMER", "CHO"],
  levels: ["All", "Beginner", "Intermediate", "Advanced"],
  tests: [
    {
      id: 1,
      title: "NORCET 9 Practice Test",
      description: "NORCET updated latest exam pattern full syllabus test",
      duration: "60 mins",
      questions: 100,
      difficulty: "Advanced",
      category: "NORCET",
      isFree: true,
    },
    {
      id: 2,
      title: "ESIC Nursing Officer Mock",
      description: "ESIC previous year style practice test",
      duration: "45 mins",
      questions: 80,
      difficulty: "Intermediate",
      category: "ESIC",
      isFree: true,
    },
    {
      id: 3,
      title: "RRB Staff Nurse Test",
      description: "Railway Recruitment Board nursing exam mock",
      duration: "50 mins",
      questions: 90,
      difficulty: "Beginner",
      category: "RRB",
      isFree: true,
    },
    {
      id: 4,
      title: "DSSSB Nursing Officer Mock 1",
      description: "Delhi DSSSB nursing officer full syllabus test",
      duration: "60 mins",
      questions: 100,
      difficulty: "Intermediate",
      category: "DSSSB",
      isFree: true,
    },
    {
      id: 5,
      title: "KGMU Staff Nurse Practice Test",
      description: "KGMU latest recruitment exam pattern test",
      duration: "60 mins",
      questions: 100,
      difficulty: "Advanced",
      category: "KGMU",
      isFree: true,
    },
    {
      id: 6,
      title: "SGPGI Nursing Officer Mock",
      description: "SGPGI previous year + conceptual questions",
      duration: "55 mins",
      questions: 95,
      difficulty: "Advanced",
      category: "SGPGI",
      isFree: true,
    },
    {
      id: 7,
      title: "RML Hospital Nursing Exam Test",
      description: "Dr RML hospital recruitment nursing mock test",
      duration: "50 mins",
      questions: 90,
      difficulty: "Intermediate",
      category: "RML",
      isFree: true,
    },
    {
      id: 8,
      title: "DHS Staff Nurse Mock Test",
      description: "Directorate of Health Services nursing exam test",
      duration: "45 mins",
      questions: 80,
      difficulty: "Beginner",
      category: "DHS",
      isFree: true,
    },
    {
      id: 9,
      title: "DMER Nursing Officer Test",
      description: "DMER state level nursing recruitment practice test",
      duration: "60 mins",
      questions: 100,
      difficulty: "Intermediate",
      category: "DMER",
      isFree: true,
    },
    {
      id: 10,
      title: "CHO Community Health Officer Mock",
      description: "CHO NHM exam preparation practice test",
      duration: "40 mins",
      questions: 75,
      difficulty: "Beginner",
      category: "CHO",
      isFree: true,
    },
  ],
};

export const FREE_TESTS_CONFIG = {
  searchPlaceholder: "Search exams (NORCET, DSSSB, CHO...)",
  noResultsMessage: "No tests found matching your filters.",
};