export const TEST_CATEGORIES = [
  {
    id: "live",
    title: "Live Tests",
    subtitle: "Attend real-time exams",
    count: 12,
    colors: ["#2563EB", "#06B6D4"],
    screen: "LiveTests",
    icon: require("../assets/images/live.png"),
  },
  {
    id: "free",
    title: "Free Tests",
    subtitle: "Practice without cost",
    count: 25,
    colors: ["#F97316", "#F59E0B"],
    screen: "FreeTests",
    icon: require("../assets/images/free.png"),
  },
  {
    id: "subject",
    title: "Subject Wise",
    subtitle: "Tests by subject",
    count: 18,
    colors: ["#DC2626", "#EF4444"],
    screen: "SubjectTests",
    icon: require("../assets/images/subject.png"),
  },
  {
    id: "topic",
    title: "Topic Based",
    subtitle: "Topic level practice",
    count: 30,
    colors: ["#16A34A", "#22C55E"],
    screen: "TopicTests",
    icon: require("../assets/images/topic.png"),
  },
  {
    id: "pyq",
    title: "Previous Year Papers",
    subtitle: "Past exam questions",
    count: 40,
    colors: ["#7C3AED", "#9333EA"],
    screen: "PreviousYear",
    icon: require("../assets/images/pyq.png"),
  },
];